Add plugin to turn aftertouch into CC
SpotlightKid/midiomatic pull request #2
Opened 2020-09-17 11:09 UTC by jonkerj

This plugin turns (monophonic) channel pressure status messages (better known as Aftertouch) into continous controller messages. I use it to turn the aftertouch of my MIDI keyboard into a mod wheel, since a lot of synths do not implement AT.

2020-09-17 13:51 UTC, SpotlightKid requested changes
Many thanks for the PR! Looks good.

Please add a section for the plugin to the README (behind MIDIPBToCC):

```
### MIDI PressureToCC

Convert (monophonic) Channel Presszre (Aftertouch) into Control Change messages

![MIDI PressureToCC screenshot](screenshots/MIDIPressureToCC.png)

... short description ..
```

I'll do the screenshot, so that the style matches the other ones.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/DistrhoPluginInfo.h
> + * MIDI PBToCC plugin based on DISTRHO Plugin Framework (DPF)
"MIDI PBToCC" -> "MIDI PressureToCC"

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/DistrhoPluginInfo.h
> + * Copyright (C) 2019 Christopher Arndt <info@chrisarndt.de>
Copyright (C) 2020 Christopher Arndt <info@chrisarndt.de>, Jorik Jonker

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/DistrhoPluginInfo.h
> +#define DISTRHO_PLUGIN_NAME         "MIDI Channel Pressure (Aftertouch) to CC"
That's a bit too long (This is gonna show up in the Hosts's plugin list).

Recommendation: "MIDI Pressure to CC"

Unfortunately, DPF doesn't support plugin descriptions via `rdfs:comment` [yet](https://github.com/DISTRHO/DPF/issues/230), but it's there in the `getDescription` method, if and when it does.

For now, let's just put the additional keywords in the description in the README.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.cpp
> + * MIDI PBToCC plugin based on DISTRHO Plugin Framework (DPF)
Same comments as for the `DistrhoPluginInfo.h` file header apply.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.cpp
> +            parameter.name = "Target CC";
Please call this "Destination CC", as I have another plugin coming up, where I use that term.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.cpp
> +            parameter.symbol = "cc";
Rename to `dest_cc` for clarity.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.cpp
> +	    cc_event.data[0] = MIDI_CONTROL_CHANGE | chan;
No tabs please.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.cpp
> +                           const MidiEvent* events, uint32_t eventCount) {
Please line up indentation, i.e. `const`, below `const`.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.hpp
> + * Copyright (C) 2019 Christopher Arndt <info@chrisarndt.de>
See 2nd comment for the `DistrhoPluginInfo.h` file header.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.hpp
> +#define PLUGIN_MIDIPressureTOCC_H
Please use ALL_CAPS for the inclusion guard.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.hpp
> +        paramCC,
Please rename to `paramDestCC` for clarity.

Don't forget to fix other occurrences too.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.hpp
> +        return "Convert Monophonic Channel Pressure (Aftertouch) into Control Change messages";
I wouldn't use title case here, so "monophonic" should be lower case as it's not part of the proper event name "Channel Pressure".

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.hpp
> +        return d_version(1, 2, 2);
Please start with version 1.0.0, I'll up the version to one indicating stable one, when I make a release.

2020-09-17 13:51 UTC, SpotlightKid commented on plugins/MIDIPressureToCC/PluginMIDIPressureToCC.hpp
> +    {
Maybe add a preset for "Foot Controller" too?

2020-09-17 15:13 UTC, jonkerj commented
All comments made sense, most of them were due to hasty replacements on my side. I think I've fixed them all, but you should probably check :-)

2020-09-17 15:40 UTC, SpotlightKid commented on README.md
> +* Original Pitch Bend messages in the input range can be optionally kept as
s/Pitch Bend/Channel Pressure/

2020-09-17 15:40 UTC, SpotlightKid commented on README.md
> +* Original Pitch Bend messages in the input range can be optionally kept as
d/in the input range/

2020-09-20 06:20 UTC, SpotlightKid commented
@jonkerj Can you fix the readme? Then I'll merge rightaway.

2020-09-21 06:52 UTC, jonkerj commented
It is fixed

2020-09-21 06:55 UTC, SpotlightKid commented
Still says "Pitch Bend" instead of "Channel Pressure".

2020-09-21 08:05 UTC, jonkerj commented
I tried to do this while having a meeting, sorry for my sloppyness. Force-pushed, hopefully OK now. Thanks for being patient and careful :-)

2020-09-21 11:46 UTC, SpotlightKid approved these changes

2020-09-21 11:47 UTC, merged

2020-09-21 11:57 UTC, SpotlightKid commented
Thanks for your contribution!

I also added a screenshot.